### ISSUE TITLE
Platzverweisort "Weazel News" hinzufügen

### ISSUE THREAD

**Issue by Marczzzz** [Vio-V-Los-Santos-Sheriffs-Department/StaatsfraktionsBugTracker#10]
**Beschreibung**
Beschreibung des Vorschlags
Platzverweisort "Weazel News" hinzufügen.
Weiß nicht inwiefern das Funktioniert / in Ordnung ist. Gib mir einfach mal Bescheid xd

**Comment by pdjip** [comment]
Weazel News als Location hinzugefügt.
