### ISSUE TITLE
Platzverweise bearbeiten

### ISSUE THREAD

**Issue by Drzorgon** [Vio-V-Los-Santos-Sheriffs-Department/StaatsfraktionsBugTracker#8]
Es wäre Super wenn man seinen Platzverweis bearbeiten kann für den Fall, das man einen Rechtschreibfehler bei dem Namen z.B. macht. Dann kann es ziemlich nervig sein den gesamten Platzverweis neu zu machen. Vorallem wenn man mehrere gründe angibt.

**Comment by pdjip** [comment]
done
